ExamMvc/Areas/Admin/Controllers/SettingController.cs
using Business.Exceptions;
using Business.Services.Abstracts;
using Business.Services.Concretes;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;

namespace Pronia.Areas.Admin.Controllers;


[Area("Admin")]
[Authorize(Roles = "Admin")]

public class SettingController : Controller
{
    private readonly ISettingService _settingService;

    public SettingController(SettingService settingService)
    {
        _settingService = settingService;
    }

    public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 2)
    {
        if (pageIndex <= 0)
        {
            pageIndex = 1;
        }
        else if (pageSize <= 0)
        {
            pageSize = 2;
        }

        var settings = await _settingService.GetPagedSettingsAsync(pageIndex,pageSize);

        return View(settings);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(Setting setting)
    {
        await _settingService.CreateSettingAsync(setting);

        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        try
        {
            _settingService.DeleteSetting(id);
        }
        catch (EntityNullException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
        return Ok();
    }
    public IActionResult Update(int id)
    {
        var existSetting = _settingService.GetSetting(x => x.Id == id && x.DeletedDate == null);
        if (existSetting is null)
        {
            return NotFound();
        }
        return View(existSetting);
    }
    [HttpPost]
    public IActionResult Update(Setting setting)
    {
        if (setting is null)
        {
            return NotFound();
        }
        else if (!ModelState.IsValid)
        {
            return View();
        }
        try
        {
            _settingService.UpdateSetting(setting.Id, setting);
        }
        catch (EntityNullException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }


        return RedirectToAction("Index");

    }
}

ExamMvc/Areas/Admin/Views/Setting/Create.cshtml
@using Core.Models

@model Setting
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" asp-action="Create">
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label">Key</label>
                    <input asp-for="Key" type="text" class="form-control" placeholder="Eli Gozel">
                    <span asp-validation-for="Key" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="inputPassword" class="col-sm-2 col-form-label">Value</label>
                    <input asp-for="Value" type="text" class="form-control" placeholder="Eli Gozel">
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
                <a asp-action="Index" class="btn btn-info">Cancel</a>

            </form>
        </div>
    </div>
</div>

ExamMvc/Areas/Admin/Views/Setting/Index.cshtml
@using Core.Models
@model IEnumerable<Setting>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Key)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Value)</th>
            <th scope="col">Actions</th>
            <th>
                <a asp-action="create" asp-controller="Setting" type="button" class="btn btn-outline-success">Create</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <th scope="row">@item.Id</th>
                <td>@item.Key</td>
                <td>@item.Value</td>
                <td>
                    <a type="button" asp-action="Update" asp-controller="Setting" asp-route-id="@item.Id" class="btn btn-outline-warning">Update</a>
                    <a type="button" asp-action="Delete" asp-controller="Setting" asp-route-id="@item.Id" class="deleteBtn btn btn-outline-danger">Delete</a>
                </td>


            </tr>
        }
    </tbody>
</table>

ExamMvc/Areas/Admin/Views/Setting/Update.cshtml
@using Core.Models

@model Setting
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" asp-action="Update">
                <div class="mb-3">
                    <label class="col-sm-2 col-form-label">Key</label>
                    <input asp-for="Key" type="text" class="form-control" placeholder="Eli Gozel">
                    <span asp-validation-for="Key" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="inputPassword" class="col-sm-2 col-form-label">Value</label>
                    <input asp-for="Value" type="text" class="form-control" placeholder="Eli Gozel">
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
                <a asp-action="Index" class="btn btn-info">Cancel</a>

            </form>
        </div>
    </div>
</div>